; V1.01

global PositionMap := Map(
    "TpButton", {Macros:["All"], Position:[118, 200], Version:"BF_V1.0.0"},
    "TpButtonTL", {Macros:["All"], Position:[112, 216], Version:"BF_V1.0.0"},
    "TpButtonBR", {Macros:["All"], Position:[120, 223], Version:"BF_V1.0.0"},
    "TpButtonCheckTL", {Macros:["All"], Position:[63, 133], Version:"BF_V1.0.0"},
    "TpButtonCheckBR", {Macros:["All"], Position:[82, 148], Version:"BF_V1.0.0"},
    "SearchField", {Macros:["All"], Position:[621, 136], Version:"BF_V1.0.0"},
    "SearchFieldTL", {Macros:["All"], Position:[596, 125], Version:"BF_V1.0.0"},
    "SearchFieldBR", {Macros:["All"], Position:[696, 146], Version:"BF_V1.0.0"},
    "TpMiddle", {Macros:["All"], Position:[231, 229], Version:"BF_V1.0.0"},
    "StupidCatTL", {Macros:["All"], Position:[357, 308], Version:"BF_V1.0.0"},
    "StupidCatBR", {Macros:["All"], Position:[435, 384], Version:"BF_V1.0.0"},
    "MiniX", {Macros:["All"], Position:[632, 144], Version:"BF_V1.0.0"},
    "MiniXTL", {Macros:["All"], Position:[606, 120], Version:"BF_V1.0.0"},
    "MiniXBR", {Macros:["All"], Position:[659, 167], Version:"BF_V1.0.0"},
    "X", {Macros:["All"], Position:[757, 144], Version:"BF_V1.0.0"},
    "XTL", {Macros:["All"], Position:[730, 114], Version:"BF_V1.0.0"},
    "XBR", {Macros:["All"], Position:[784, 168], Version:"BF_V1.0.0"},
    "OkayButton", {Macros:["All"], Position:[408, 459], Version:"BF_V1.0.0"},
    "InventoryBackpackButton", {Macros:["MultiMacro", "RankQuestMacro"], Position:[36, 232], Version:"MM_V4.0.0"},
    "TopOfGame", {Macros:["MultiMacro", "RankQuestMacro"], Position:[404, 38], Version:"MM_V4.0.0"},
    "ItemMiddle", {Macros:["MultiMacro", "RankQuestMacro"], Position:[127, 268], Version:"MM_V4.0.0"},
    "SecondaryItemMiddle", {Macros:["MultiMacro", "RankQuestMacro"], Position:[230, 261], Version:"MM_V4.0.0"},
    "ItemTL", {Macros:["MultiMacro", "RankQuestMacro"], Position:[78, 224], Version:"MM_V4.0.0"},
    "ItemBR", {Macros:["MultiMacro", "RankQuestMacro"], Position:[157, 301], Version:"MM_V4.0.0"},
    "YesButton", {Macros:["MultiMacro", "RankQuestMacro"], Position:[294, 455], Version:"MM_V4.0.0"},
    "YesButtonTL", {Macros:["MultiMacro", "RankQuestMacro"], Position:[207, 422], Version:"BF_V1.0.0"},
    "YesButtonBR", {Macros:["MultiMacro", "RankQuestMacro"], Position:[390, 481], Version:"BF_V1.0.0"},
    "MiddleOfScreen", {Macros:["MultiMacro", "RankQuestMacro"], Position:[410,320], Version:"MM_V4.0.0"},
    "SuperComputer_TopMiddle", {Macros:["MultiMacro", "RankQuestMacro"], Position:[412, 161], Version:"MM_V4.0.0"},
    "SpawnButton", {Macros:["MultiMacro", "RankQuestMacro"], Position:[32, 272], Version:"MM_V4.0.0"},
    "TechButton", {Macros:["TreeHouseMacro"], Position:[28, 313], Version:"THM_V2.0.0"},
    "VoidButton", {Macros:["TreeHouseMacro"], Position:[32, 363], Version:"THM_V2.0.0"},
    "AutoHatch", {Macros:["MultiMacro", "RankQuestMacro"], Position:[112, 280], Version:"MM_V4.0.0"},
    "AutoHatchTL", {Macros:["MultiMacro", "RankQuestMacro"], Position:[119, 256], Version:"MM_V4.0.0"},
    "AutoHatchBR", {Macros:["MultiMacro", "RankQuestMacro"], Position:[137, 268], Version:"MM_V4.0.0"},
    "AutoHatch_InternalCheck", {Macros:["MultiMacro", "RankQuestMacro"], Position:[462, 224], Version:"MM_V4.0.0"},
    "AutoHatch_InternalChargedCheck", {Macros:["MultiMacro", "RankQuestMacro"], Position:[462, 326], Version:"MM_V4.0.0"},
    "AutoHatch_InternalGoldenCheck", {Macros:["MultiMacro", "RankQuestMacro"], Position:[462, 432], Version:"MM_V4.0.0"},
    "AutoHatch_Enable", {Macros:["MultiMacro", "RankQuestMacro"], Position:[517, 222], Version:"MM_V4.0.0"},
    "AutoHatch_Charged", {Macros:["MultiMacro", "RankQuestMacro"], Position:[516, 326], Version:"MM_V4.0.0"},
    "AutoHatch_Golden", {Macros:["MultiMacro", "RankQuestMacro"], Position:[519, 432], Version:"MM_V4.0.0"},
    "AutoFarm", {Macros:["MultiMacro", "RankQuestMacro"], Position:[51, 342], Version:"MM_V4.0.0"},
    "AutoFarmTL", {Macros:["MultiMacro", "RankQuestMacro"], Position:[60, 321], Version:"MM_V4.0.0"},
    "AutoFarmBR", {Macros:["MultiMacro", "RankQuestMacro"], Position:[70, 330], Version:"MM_V4.0.0"},
    "EggMaxBuy", {Macros:["MultiMacro", "RankQuestMacro"], Position:[555, 464], Version:"MM_V4.0.0"},
    "SuperComputer_EmpowerEnchantButton", {Macros:["MultiMacro", "RankQuestMacro"], Position:[267, 207], Version:"MM_V4.0.0"},
    "SuperComputer_DaycareButton", {Macros:["MultiMacro", "RankQuestMacro"], Position:[549, 437], Version:"MM_V4.0.0"},
    "InventoryEnchantsButton", {Macros:["MultiMacro"], Position:[31, 318], Version:"MM_V4.0.0"},
    "EnchantEquipSlot1", {Macros:["MultiMacro"], Position:[368, 212], Version:"MM_V4.0.0"},
    "Empower_EnchantSelectionTL", {Macros:["MultiMacro"], Position:[311, 191], Version:"MM_V4.0.0"},
    "Empower_EnchantSelectionBR", {Macros:["MultiMacro"], Position:[751, 494], Version:"MM_V4.0.0"},
    "Empower_OkayButton", {Macros:["MultiMacro"], Position:[180, 447], Version:"MM_V4.0.0"},
    "Empower_OkayButtonTL", {Macros:["MultiMacro"], Position:[97, 416], Version:"MM_V4.0.0"},
    "Empower_OkayButtonBR", {Macros:["MultiMacro"], Position:[259, 474], Version:"MM_V4.0.0"},
    "Daycare_PetSelection", {Macros:["MultiMacro"], Position:[453, 246], Version:"MM_V4.0.0"},
    "Daycare_OkayButton", {Macros:["MultiMacro"], Position:[210, 468], Version:"MM_V4.0.0"},
    "Daycare_OkayButtonTL", {Macros:["MultiMacro"], Position:[132, 441], Version:"MM_V4.0.0"},
    "Daycare_OkayButtonBR", {Macros:["MultiMacro"], Position:[291, 490], Version:"MM_V4.0.0"},
    "Daycare_EnrollButtonTL", {Macros:["MultiMacro"], Position:[59, 399], Version:"MM_V4.0.0"},
    "Daycare_EnrollButtonBR", {Macros:["MultiMacro"], Position:[753, 480], Version:"MM_V4.0.0"},
    "DaycareGP_EnrollButtonTL", {Macros:["MultiMacro"], Position:[59, 381], Version:"MM_V4.0.0"},
    "DaycareGP_EnrollButtonBR", {Macros:["MultiMacro"], Position:[753, 455], Version:"MM_V4.0.0"},
    "FreeGiftsButton", {Macros:["MultiMacro"], Position:[49, 220], Version:"MM_V4.0.0"},
    "DisconnectBG_LS", {Macros:["MultiMacro"], Position:[212, 337], Version:"MM_V4.0.0"},
    "DisconnectBG_RS", {Macros:["MultiMacro"], Position:[599, 337], Version:"MM_V4.0.0"},
    "ReconnectButton", {Macros:["MultiMacro"], Position:[546, 420], Version:"MM_V4.0.0"},
    "LB_Star", {Macros:["MultiMacro"], Position:[676, 83], Version:"MM_V4.0.0"},
    "LB_Diamond", {Macros:["MultiMacro"], Position:[728, 81], Version:"MM_V4.0.0"},
    "UpperMiddle", {Macros:["MultiMacro"], Position:[502, 41], Version:"MM_V4.0.0"},
)

global X_PositionMap := Map(
    "GiftX1", 241,
    "GiftX2", 350,
    "GiftX3", 465,
    "GiftX4", 580,
    "Empower_EnchantX1", 375,
    "Empower_EnchantX2", 476,
    "Empower_EnchantX3", 577,
    "Empower_EnchantX4", 676,
)

global Y_PositionMap := Map(
    "GiftY1", 195,
    "GiftY2", 290,
    "GiftY3", 390,
    "Empower_EnchantY1", 215,
    "Empower_EnchantY2", 310,
    "Empower_EnchantY3", 410,
)
